[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 40 }
opacity = 1.00
decorations = "none"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 15

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
]

[general]
import = [ "themes/monokai.toml" ]

[terminal]
shell = { program = "/bin/bash", args = ["-l", "-c", "tmux attach || tmux"] }

