import = [ "~/.config/alacritty/themes/gnome-terminal.toml" ]

shell = { program = "/bin/bash", args = ["-l", "-c", "tmux attach || tmux"] }

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Fullscreen"
padding = { x = 5, y = 5 }
opacity = 1.0

[font]
normal = { family = "Source Code Pro" }
size = 17

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
]

