""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Source files
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/general.vim
source $HOME/.vim/config/autocmd.vim
source $HOME/.vim/config/mappings.vim
source $HOME/.vim/config/status.vim
