
[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 150, lines = 40 }
opacity = 0.95

[font]
normal = { family = " DejaVu Sans Mono" }
size = 15

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
]

[general]
import = [ "~/.config/alacritty/themes/white-on-black.toml" ]

[terminal]

shell = { program = "/bin/bash", args = ["-l", "-c", "tmux attach || tmux"] }

